name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: xvfb-run -a npm test

      - name: Package extension
        run: npx @vscode/vsce package -o tab-numbering.vsix

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tab-numbering
          path: tab-numbering.vsix
